//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    
    public partial class BetweenMatchInfo
    {
        public BetweenMatchInfo()
        {
            this.PartName = "\"\"";
            this.Modified = new ElementContext();
            this.Original = new ElementContext();
        }
    
        public string PartName { get; set; }
    
        public ElementContext Modified { get; set; }
        public ElementContext Original { get; set; }
    }
}
