//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    
    public enum CaseKind : int
    {
        LowOutlier = 1,
        HighOutlier = 2,
        Unknown = 0,
        SamplingAll = 3,
        SamplingMedianCloser = 4,
        SamplingNonOutliers = 5,
        SamplingNormal = 6,
        MissedMatchesDI = 7,
        MissedMatchesDU = 8,
        MissedMatchesUI = 9,
        MissedMatchesUU = 10,
        MissedMatchesDM = 11,
        MissedMatchesMI = 12,
        MissedMatchesMM = 13,
        MissedMatchesUM = 14,
        MissedMatchesMU = 15,
        MissedMatchesM = 16,
        Symptom = 17
    }
}
