//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    
    public enum ChangeDetectionApproaches : int
    {
        Manually = 0,
        Simetrics = 1,
        NativeGumTree = 2,
        NativeGumTreeWithoutComments = 3,
        NativeGumTreeMethodsWithoutComments = 4,
        InverseOfNativeGumTree = 5,
        NativeGumTreeWithChangeDistillerMatcher = 6,
        InverseOfNativeGumTreeWithChangeDistillerMatcher = 7,
        NativeGumTreeWithXyMatcher = 8,
        InverseOfNativeGumTreeWithXyMatcher = 9,
        NativeGTtreefiedRoslynML = 10,
        InverseNativeGTtreefiedRoslynML = 11,
        NativeGTtreefiedRoslynMLWithMinH2Sim0d5Size100 = 12,
        NativeGTtreefiedRoslynMLWithMinH2Sim0d5Size325 = 13,
        NativeGTtreefiedRoslynMLWithMinH2Sim0d5Size550 = 14,
        NativeGTtreefiedRoslynMLWithMinH2Sim0d5Size775 = 15,
        NativeGTtreefiedRoslynMLWithMinH2Sim0d5Size1225 = 16,
        NativeGTtreefiedRoslynMLWithMinH2Sim0d5Size1450 = 17,
        NativeGTtreefiedRoslynMLWithMinH2Sim0d5Size1675 = 18,
        NativeGTtreefiedRoslynMLWithMinH2Sim0d5Size1900 = 19,
        InverseNativeGTtreefiedRoslynMLWithMinH2Sim0d5Size100 = 20,
        InverseNativeGTtreefiedRoslynMLWithMinH2Sim0d5Size325 = 21,
        InverseNativeGTtreefiedRoslynMLWithMinH2Sim0d5Size550 = 22,
        InverseNativeGTtreefiedRoslynMLWithMinH2Sim0d5Size775 = 23,
        InverseNativeGTtreefiedRoslynMLWithMinH2Sim0d5Size1225 = 24,
        InverseNativeGTtreefiedRoslynMLWithMinH2Sim0d5Size1450 = 25,
        InverseNativeGTtreefiedRoslynMLWithMinH2Sim0d5Size1675 = 26,
        InverseNativeGTtreefiedRoslynMLWithMinH2Sim0d5Size1900 = 27,
        NativeGTtreefiedRoslynMLWithBasicPruning = 28,
        InverseNativeGTtreefiedRoslynMLWithBasicPruning = 29,
        NativeGTtreefiedRoslynMLWithBasicPruningAndIncludeTrivia = 30,
        InverseNativeGTtreefiedRoslynMLWithBasicPruningAndIncludeTrivia = 31,
        NativeGTtreefiedRoslynMLWithIncludeTrivia = 32,
        InverseNativeGTtreefiedRoslynMLWithIncludeTrivia = 33,
        NativeGTtreefiedRoslynMLWithBasicPruningDefoliation = 34,
        InverseNativeGTtreefiedRoslynMLWithBasicPruningDefoliation = 35,
        NativeGTtreefiedRoslynMLWithBasicPruningDefoliationAndIncludeTrivia = 36,
        InverseNativeGTtreefiedRoslynMLWithBasicPruningDefoliationAndIncludeTrivia = 37
    }
}
