//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    
    [Flags]
    public enum CodeCategory : short
    {
        Maintained = 1,
        Generated = 2,
        Library = 4,
        Example = 8,
        Unused = 16,
        Temporary = 32,
        Extraneous = 64,
        Decompiled = 128,
        Production = 256,
        Test = 512
    }
}
