//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class CoexistenceSymptom : Symptom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoexistenceSymptom()
        {
            this.Original = new ElementContext();
            this.Modified = new ElementContext();
            this.CoexistingOriginal = new ElementContext();
        }
    
    
        public ElementContext Original { get; set; }
        public ElementContext Modified { get; set; }
        public ElementContext CoexistingOriginal { get; set; }
    }
}
