//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeltaContentSummary
    {
        public System.Guid Id { get; set; }
        public string Annotations { get; set; }
        public int Approach { get; set; }
        public Nullable<long> Modified { get; set; }
        public Nullable<long> Original { get; set; }
    
        public virtual Delta Delta { get; set; }
    }
}
