//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    
    public partial class ElementDescription
    {
        public ElementDescription()
        {
            this.Type = "\"\"";
            this.Id = "\"-1\"";
        }
    
        public string Type { get; set; }
        public string Id { get; set; }
        public string Hint { get; set; }
    }
}
