//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    
    [Flags]
    public enum FileFormatKind : long
    {
        Gumtreefied = 1,
        SrcML = 2,
        RoslynML = 4,
        NONE = 0,
        BasicPruning = 8,
        IncludeTrivia = 16,
        Defoliation = 32
    }
}
