//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GitRepository : DbContext
    {
        public GitRepository()
            : base("name=GitRepository")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RepositoryObject> RepositoryObjects { get; set; }
        public virtual DbSet<FileContent> FileContents { get; set; }
        public virtual DbSet<FileContentSummary> FileContentSummaries { get; set; }
        public virtual DbSet<Delta> Deltas { get; set; }
        public virtual DbSet<FileRevisionPair> FileRevisionPairs { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<FileFormat> FileFormats { get; set; }
        public virtual DbSet<DeltaContentSummary> DeltaContentSummaries { get; set; }
    }
}
