//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RLMatchSymptom : BetweenSymptom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RLMatchSymptom()
        {
            this.Right = new BetweenMatchInfo();
            this.OriginalAtLeft = new BetweenMatchInfo();
            this.ModifiedAtLeft = new BetweenMatchInfo();
            this.NullLeft = new BetweenMatchInfo();
        }
    
    
        public BetweenMatchInfo Right { get; set; }
        public BetweenMatchInfo OriginalAtLeft { get; set; }
        public BetweenMatchInfo ModifiedAtLeft { get; set; }
        private BetweenMatchInfo NullLeft { get; set; }
    }
}
