
                                                    // Generated helper templates
                                                    // Generated items
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SwitchLabelSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DefaultSwitchLabelSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CaseSwitchLabelSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CasePatternSwitchLabelSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\VariableDesignationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ParenthesizedVariableDesignationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DiscardDesignationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SingleVariableDesignationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\StatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CommonForEachStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ForEachVariableStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ForEachStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TryStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SwitchStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\IfStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LockStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\UnsafeStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CheckedStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\FixedStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\UsingStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ForStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DoStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\WhileStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\YieldStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ThrowStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ReturnStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ContinueStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BreakStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\GotoStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LabeledStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\EmptyStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ExpressionStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LocalDeclarationStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LocalFunctionStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BlockSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InterpolatedStringContentSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InterpolationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InterpolatedStringTextSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\PatternSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConstantPatternSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DeclarationPatternSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SelectOrGroupClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\GroupClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SelectClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\QueryClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\OrderByClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\WhereClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\JoinClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LetClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\FromClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseArgumentListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BracketedArgumentListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ArgumentListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AnonymousFunctionExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LambdaExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ParenthesizedLambdaExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SimpleLambdaExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AnonymousMethodExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InstanceExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ThisExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\NameSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SimpleNameSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\GenericNameSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\IdentifierNameSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AliasQualifiedNameSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\QualifiedNameSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\RefTypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\OmittedTypeArgumentSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TupleTypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\NullableTypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\PointerTypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ArrayTypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\PredefinedTypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ThrowExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\IsPatternExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InterpolatedStringExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\OmittedArraySizeExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\QueryExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\StackAllocArrayCreationExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ImplicitArrayCreationExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ArrayCreationExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AnonymousObjectCreationExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ObjectCreationExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InitializerExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\RefExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CastExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DeclarationExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ElementAccessExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InvocationExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SizeOfExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeOfExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DefaultExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CheckedExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\RefValueExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\RefTypeExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\MakeRefExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LiteralExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConditionalExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AssignmentExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BinaryExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ImplicitElementAccessSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ElementBindingExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\MemberBindingExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConditionalAccessExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\MemberAccessExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\PostfixUnaryExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AwaitExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\PrefixUnaryExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TupleExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ParenthesizedExpressionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlAttributeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlNameAttributeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlCrefAttributeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlTextAttributeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlNodeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlCommentSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlProcessingInstructionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlCDataSectionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlTextSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlEmptyElementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlElementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseCrefParameterListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CrefBracketedParameterListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CrefParameterListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CrefSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\MemberCrefSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConversionOperatorMemberCrefSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\OperatorMemberCrefSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\IndexerMemberCrefSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\NameMemberCrefSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\QualifiedCrefSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeCrefSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\StructuredTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BranchingDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConditionalDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ElifDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\IfDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ElseDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ShebangDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LoadDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ReferenceDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\PragmaChecksumDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\PragmaWarningDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\LineDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\UndefDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DefineDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BadDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\WarningDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ErrorDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\EndRegionDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\RegionDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\EndIfDirectiveTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DocumentationCommentTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SkippedTokensTriviaSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseParameterListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BracketedParameterListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ParameterListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeParameterConstraintSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeConstraintSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ClassOrStructConstraintSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConstructorConstraintSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseTypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SimpleBaseTypeSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\MemberDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BasePropertyDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\IndexerDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\EventDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\PropertyDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseMethodDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DestructorDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConstructorDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConversionOperatorDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\OperatorDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\MethodDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseFieldDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\EventFieldDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\FieldDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseTypeDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InterfaceDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\StructDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ClassDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\EnumDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\NamespaceDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\GlobalStatementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\IncompleteMemberSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\EnumMemberDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\DelegateDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AttributeTargetSpecifierSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AttributeListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\UsingDirectiveSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ExternAliasDirectiveSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CompilationUnitSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\FinallyClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CatchFilterClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CatchDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CatchClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\SwitchSectionSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ElseClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\EqualsValueClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\VariableDeclaratorSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\VariableDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InterpolationFormatClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\InterpolationAlignmentClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\WhenClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\QueryContinuationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\OrderingSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\JoinIntoClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\QueryBodySyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AnonymousObjectMemberDeclaratorSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\NameColonSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ArgumentSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TupleElementSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ArrayRankSpecifierSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeArgumentListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlPrefixSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlNameSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlElementEndTagSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\XmlElementStartTagSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\CrefParameterSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ParameterSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AccessorDeclarationSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AccessorListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ArrowExpressionClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ConstructorInitializerSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\ExplicitInterfaceSpecifierSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeParameterConstraintClauseSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\BaseListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeParameterSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\TypeParameterListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\NameEqualsSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AttributeArgumentSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AttributeArgumentListSyntax.cs
                                                    // E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.CSharp\RoslynML\AttributeSyntax.cs
