//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    
    public partial class BetweenPartInfo
    {
        public BetweenPartInfo()
        {
            this.Parent4IDU_Original4U = new ElementContext();
            this.Element4IDM_Modified4U = new ElementContext();
        }
    
        public string PartName { get; set; }
        public string Operation { get; set; }
    
        public ElementContext Parent4IDU_Original4U { get; set; }
        public ElementContext Element4IDM_Modified4U { get; set; }
    }
}
