//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeltaComparison
    {
        public System.Guid LeftId { get; set; }
        public System.Guid RightId { get; set; }
        public string Matching { get; set; }
        public string Differencing { get; set; }
    
        public virtual Delta Left { get; set; }
        public virtual Delta Right { get; set; }
    }
}
