//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    
    public partial class ElementContext
    {
        public ElementContext()
        {
            this.Element = new ElementDescription();
        }
    
        public string ScopeHint { get; set; }
    
        public ElementDescription Element { get; set; }
    }
}
