//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileContentSummary
    {
        public System.Guid Id { get; set; }
        public long Size { get; set; }
        public Nullable<long> TotalLines { get; set; }
        public Nullable<long> BlankLines { get; set; }
        public Nullable<long> CommentLines { get; set; }
        public Nullable<long> CodeLines { get; set; }
        public Nullable<long> StatementLines { get; set; }
        public string SyntaxKindAnnotations { get; set; }
        public string Annotations { get; set; }
        public Nullable<CodeCategory> CodeCategory { get; set; }
    
        public virtual FileVersion FileVersion { get; set; }
    }
}
