//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class MissedElementSymptom : Symptom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MissedElementSymptom()
        {
            this.Original = new MissedMatch();
            this.Modified = new MissedMatch();
        }
    
        public string Pattern { get; set; }
    
        public MissedMatch Original { get; set; }
        public MissedMatch Modified { get; set; }
    }
}
