//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    
    public enum RedundancyPattern : byte
    {
        DI = 1,
        UI = 2,
        DU = 3,
        UU = 4,
        DM = 5,
        MI = 6,
        MM = 7,
        UM = 8,
        MU = 9,
        UMI = 10,
        DUM = 11,
        UMU = 12,
        UUM = 13,
        UMUM = 14,
        MUM = 15,
        UMM = 16
    }
}
