//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedundancySymptom : Symptom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RedundancySymptom()
        {
            this.MissedOriginal = new ElementDescription();
            this.SpuriousOriginal = new ElementDescription();
            this.MissedModified = new ElementDescription();
            this.SpuriousModified = new ElementDescription();
            this.AndSpuriousOriginal = new ElementDescription();
            this.AndSpuriousModified = new ElementDescription();
        }
    
        public RedundancyPattern Pattern { get; set; }
        public ChangeDetectionApproaches DeltaApproach { get; set; }
        public ChangeDetectionApproaches CorrectorApproach { get; set; }
    
        public ElementDescription MissedOriginal { get; set; }
        public ElementDescription SpuriousOriginal { get; set; }
        public ElementDescription MissedModified { get; set; }
        public ElementDescription SpuriousModified { get; set; }
        public ElementDescription AndSpuriousOriginal { get; set; }
        public ElementDescription AndSpuriousModified { get; set; }
    }
}
