//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    
    public enum ReviewKind : int
    {
        Ratio_LevenshteinGumTree_IgnoringCommentChanges_LocalOutliers = 3,
        Ratio_LevenshteinGumTree_RejectOnlyCommentChanges_Outliers = 2,
        Ratio_LevenshteinGumTree_Outliers = 1,
        Ratio_LevenshteinGumTreeAdditions_LocalOutliers = 4,
        MissedNameMatches = 5,
        Ratio_LevenshteinGumTreeDeletions_LocalOutliers = 6,
        Redundancy_MissedName = 7,
        Spuriosity_IncompatibleMatches = 8,
        Spuriosity_SpuriousElements = 9
    }
}
