//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    
    public enum ReviewSeverity : int
    {
        Good = 2,
        GoodBut = 1,
        Unclear = 0,
        Bad = 3,
        Attention = 4,
        Found = 5
    }
}
