//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.Common.DBModel
{
    using System;
    
    [Flags]
    public enum Topics : short
    {
        Domain = 1,
        Matching = 2,
        Differencing = 4,
        Report = 8,
        None = 0
    }
}
