//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    
    public partial class BetweenPartInfo
    {
        public BetweenPartInfo()
        {
            this.OriginalOrParent = new ElementContext();
            this.ModifiedOrElement = new ElementContext();
        }
    
        public string PartName { get; set; }
    
        public ElementContext OriginalOrParent { get; set; }
        public ElementContext ModifiedOrElement { get; set; }
    }
}
