//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetweenSymptom : Symptom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BetweenSymptom()
        {
            this.Left = new BetweenPartInfo();
            this.Right = new BetweenPartInfo();
        }
    
        public string Pattern { get; set; }
    
        public BetweenPartInfo Left { get; set; }
        public BetweenPartInfo Right { get; set; }
    }
}
