//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    
    public enum ChangeDetectionApproaches : int
    {
        Manually = 0,
        Simetrics = 1,
        NativeGumTree = 2,
        NativeGumTreeWithoutComments = 3,
        NativeGumTreeMethodsWithoutComments = 4,
        InverseOfNativeGumTree = 5,
        NativeGumTreeWithChangeDistillerMatcher = 6,
        InverseOfNativeGumTreeWithChangeDistillerMatcher = 7,
        NativeGumTreeWithXyMatcher = 8,
        InverseOfNativeGumTreeWithXyMatcher = 9
    }
}
