//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    
    [Flags]
    public enum CodeCategory : byte
    {
        MaintainedProduction = 1,
        MaintainedTest = 9,
        GeneratedProduction = 2,
        GeneratedTest = 10,
        LibraryProduction = 3,
        LibraryTest = 11,
        ExampleProduction = 4,
        ExampleTest = 12,
        UnusedProduction = 5,
        TemporaryProduction = 6,
        ExtraneousProduction = 7,
        DecompiledProduction = 8,
        UnusedTest = 13,
        TemporaryTest = 14,
        ExtraneousTest = 15,
        DecompiledTest = 16
    }
}
