//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileRevisionPair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileRevisionPair()
        {
            this.Versioning = new PairRevisionInfo();
        }
    
        public System.Guid Id { get; set; }
        public string Annotations { get; set; }
    
        public PairRevisionInfo Versioning { get; set; }
    
        public virtual FileVersion From { get; set; }
        public virtual FileVersion To { get; set; }
    }
}
