//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class FileChange
    {
        public System.Guid ParentCommitId { get; set; }
        public System.Guid FileVersionId { get; set; }
        public System.Guid ChildCommitId { get; set; }
        public int LinesAdded { get; set; }
        public int LinesDeleted { get; set; }
        public string Patch { get; set; }
        public string Annotations { get; set; }
    
        public virtual Commit ToCommit { get; set; }
        public virtual Commit FromCommit { get; set; }
        public virtual FileVersion FileVersion { get; set; }
    }
}
