//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    using System.Collections.Generic;
    
    public partial class LRMatchSymptom : BetweenSymptom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LRMatchSymptom()
        {
            this.Left = new BetweenMatchInfo();
            this.NullRight = new BetweenMatchInfo();
            this.OriginalAtRight = new BetweenMatchInfo();
            this.ModifiedAtRight = new BetweenMatchInfo();
        }
    
    
        public BetweenMatchInfo Left { get; set; }
        private BetweenMatchInfo NullRight { get; set; }
        public BetweenMatchInfo OriginalAtRight { get; set; }
        public BetweenMatchInfo ModifiedAtRight { get; set; }
    }
}
