//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    
    public partial class MissedMatch
    {
        public MissedMatch()
        {
            this.Element = new ElementDescription();
            this.AncestorOfReference = new ElementDescription();
            this.CommonAncestorOfReference = new ElementDescription();
        }
    
        public string Hint { get; set; }
        public string ScopeHint { get; set; }
    
        public ElementDescription Element { get; set; }
        public ElementDescription AncestorOfReference { get; set; }
        public ElementDescription CommonAncestorOfReference { get; set; }
    }
}
