//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    
    public partial class PairRevisionInfo
    {
        public string Path { get; set; }
        public int FromVersion { get; set; }
        public int ToVersion { get; set; }
    }
}
