//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs
{
    using System;
    
    [Flags]
    public enum SubcorpusKind : int
    {
        GlobalGeneralRatioLvGtHigherOutlier = 1,
        GlobalGeneralRatioLvGtLowerOutlier = 2,
        GlobalGeneralRatioLvGtMedianCloser = 4,
        GlobalGeneralRatioLvGtRandom = 8,
        GlobalInsertionPorcentageLvGtHigherOutlier = 16,
        GlobalInsertionPorcentageLvGtLowerOutlier = 32,
        GlobalInsertionPorcentageLvGtMedianCloser = 64,
        GlobalInsertionPorcentageLvGtRandom = 128,
        GlobalDeletionPorcentageLvGtHigherOutlier = 256,
        GlobalDeletionPorcentageLvGtLowerOutlier = 512,
        GlobalDeletionPorcentageLvGtMedianCloser = 1024,
        GlobalDeletionPorcentageLvGtRandom = 2048,
        GlobalUpdatePorcentageLvGtHigherOutlier = 4096,
        GlobalUpdatePorcentageLvGtLowerOutlier = 8192,
        GlobalUpdatePorcentageLvGtMedianCloser = 16384,
        GlobalUpdatePorcentageLvGtRandom = 32768,
        GlobalMovePorcentageLvGtHigherOutlier = 65536,
        GlobalMovePorcentageLvGtLowerOutlier = 131072,
        GlobalMovePorcentageLvGtMedianCloser = 262144,
        GlobalMovePorcentageLvGtRandom = 524288
    }
}
