//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jawilliam.CDF.Labs.VSIXProject.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullOriginalAst.xml")]
        public string FullOriginalAstPath {
            get {
                return ((string)(this["FullOriginalAstPath"]));
            }
            set {
                this["FullOriginalAstPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullModifiedAst.xml")]
        public string FullModifiedAstPath {
            get {
                return ((string)(this["FullModifiedAstPath"]));
            }
            set {
                this["FullModifiedAstPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftOriginalAst.xml")]
        public string LeftOriginalAstPath {
            get {
                return ((string)(this["LeftOriginalAstPath"]));
            }
            set {
                this["LeftOriginalAstPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftModifiedAst.xml")]
        public string LeftModifiedAstPath {
            get {
                return ((string)(this["LeftModifiedAstPath"]));
            }
            set {
                this["LeftModifiedAstPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RightOriginalAst.xml")]
        public string RightOriginalAstPath {
            get {
                return ((string)(this["RightOriginalAstPath"]));
            }
            set {
                this["RightOriginalAstPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RightModifiedAst.xml")]
        public string RightModifiedAstPath {
            get {
                return ((string)(this["RightModifiedAstPath"]));
            }
            set {
                this["RightModifiedAstPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RatedMatching.xml")]
        public string RatedMatching {
            get {
                return ((string)(this["RatedMatching"]));
            }
            set {
                this["RatedMatching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RatedDifferencing.xml")]
        public string RatedDifferencing {
            get {
                return ((string)(this["RatedDifferencing"]));
            }
            set {
                this["RatedDifferencing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OriginalForReview.cs")]
        public string OriginalFilePath {
            get {
                return ((string)(this["OriginalFilePath"]));
            }
            set {
                this["OriginalFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ModifiedForReview.cs")]
        public string ModifiedFilePath {
            get {
                return ((string)(this["ModifiedFilePath"]));
            }
            set {
                this["ModifiedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OriginalAst.xml")]
        public string OriginalAstPath {
            get {
                return ((string)(this["OriginalAstPath"]));
            }
            set {
                this["OriginalAstPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ModifiedAst.xml")]
        public string ModifiedAstPath {
            get {
                return ((string)(this["ModifiedAstPath"]));
            }
            set {
                this["ModifiedAstPath"] = value;
            }
        }
    }
}
