
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Jawilliam.CDF.Tests.Flad.Awareness
{
    [TestClass]
    public partial class RoslynMLDeltaExpanderTests { }
}


// Generated helper templates
// Generated items
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDefaultSwitchLabelSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCaseSwitchLabelSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCasePatternSwitchLabelSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderParenthesizedVariableDesignationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDiscardDesignationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderSingleVariableDesignationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderForEachVariableStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderForEachStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTryStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderSwitchStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderIfStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderLockStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderUnsafeStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCheckedStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderFixedStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderUsingStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderForStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDoStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderWhileStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderYieldStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderThrowStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderReturnStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderContinueStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderBreakStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderGotoStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderLabeledStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderEmptyStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderExpressionStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderLocalDeclarationStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderLocalFunctionStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderBlockSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderInterpolationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderInterpolatedStringTextSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderConstantPatternSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDeclarationPatternSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderGroupClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderSelectClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderOrderByClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderWhereClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderJoinClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderLetClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderFromClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderBracketedArgumentListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderArgumentListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderParenthesizedLambdaExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderSimpleLambdaExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAnonymousMethodExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderBaseExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderThisExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderGenericNameSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderIdentifierNameSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAliasQualifiedNameSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderQualifiedNameSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderRefTypeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderOmittedTypeArgumentSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTupleTypeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderNullableTypeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderPointerTypeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderArrayTypeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderPredefinedTypeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderThrowExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderIsPatternExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderInterpolatedStringExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderOmittedArraySizeExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderQueryExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderStackAllocArrayCreationExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderImplicitArrayCreationExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderArrayCreationExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAnonymousObjectCreationExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderObjectCreationExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderInitializerExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderRefExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCastExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDeclarationExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderElementAccessExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderInvocationExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderSizeOfExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTypeOfExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDefaultExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCheckedExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderRefValueExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderRefTypeExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderMakeRefExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderLiteralExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderConditionalExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAssignmentExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderBinaryExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderImplicitElementAccessSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderElementBindingExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderMemberBindingExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderConditionalAccessExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderMemberAccessExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderPostfixUnaryExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAwaitExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderPrefixUnaryExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTupleExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderParenthesizedExpressionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlNameAttributeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlCrefAttributeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlTextAttributeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlCommentSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlProcessingInstructionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlCDataSectionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlTextSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlEmptyElementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlElementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCrefBracketedParameterListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCrefParameterListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderConversionOperatorMemberCrefSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderOperatorMemberCrefSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderIndexerMemberCrefSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderNameMemberCrefSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderQualifiedCrefSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTypeCrefSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderElifDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderIfDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderElseDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderShebangDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderLoadDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderReferenceDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderPragmaChecksumDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderPragmaWarningDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderLineDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderUndefDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDefineDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderBadDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderWarningDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderErrorDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderEndRegionDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderRegionDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderEndIfDirectiveTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDocumentationCommentTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderSkippedTokensTriviaSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderBracketedParameterListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderParameterListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTypeConstraintSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderClassOrStructConstraintSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderConstructorConstraintSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderSimpleBaseTypeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderIndexerDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderEventDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderPropertyDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDestructorDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderConstructorDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderConversionOperatorDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderOperatorDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderMethodDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderEventFieldDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderFieldDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderInterfaceDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderStructDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderClassDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderEnumDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderNamespaceDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderGlobalStatementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderIncompleteMemberSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderEnumMemberDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderDelegateDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAttributeArgumentListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAttributeSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAttributeTargetSpecifierSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAttributeListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderUsingDirectiveSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderExternAliasDirectiveSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCompilationUnitSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderFinallyClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCatchFilterClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCatchDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCatchClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderSwitchSectionSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderElseClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderEqualsValueClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderVariableDeclaratorSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderVariableDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderInterpolationFormatClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderInterpolationAlignmentClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderWhenClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderQueryContinuationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderOrderingSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderJoinIntoClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderQueryBodySyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAnonymousObjectMemberDeclaratorSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderNameColonSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderArgumentSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTupleElementSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderArrayRankSpecifierSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTypeArgumentListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlPrefixSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlNameSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlElementEndTagSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderXmlElementStartTagSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderCrefParameterSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderParameterSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAccessorDeclarationSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAccessorListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderArrowExpressionClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderConstructorInitializerSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderExplicitInterfaceSpecifierSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTypeParameterConstraintClauseSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderBaseListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTypeParameterSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderTypeParameterListSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderNameEqualsSyntaxTests.cs
// E:\MyRepositories\Change-Detection-Foundation\Jawilliam.CDF.Tests\Flad.Awareness\RoslynMLDeltaExpanderAttributeArgumentSyntaxTests.cs
